### ISSUE TITLE
Hiero Link is Broken

### ISSUE THREAD

**Issue by SonicGDX** [Voycawojka/calligro#75]
The website (and README) links to here: [https://github.com/libgdx/libgdx/wiki/Hiero](https://github.com/libgdx/libgdx/wiki/Hiero)
But the libGDX wiki was moved to libgdx.com so the link is broken.
The new link is here: [https://libgdx.com/wiki/tools/hiero](https://libgdx.com/wiki/tools/hiero)

**Comment by Voycawojka** [comment]
Thanks for reporting. It's fixed now
